### ISSUE TITLE
Response handler

### ISSUE THREAD

**Issue by mvolotov** [DNAmaster10/httpRequests#6]
Hello! I think it would be great to finish the response handler. I really liked your solution with the JS handler, but I would like to expand its capabilities.

For example, in addition to sending commands to the console, be able to send messages to the player. To do this, you can make a prefix by which the plugin understands what it needs to do, like:
```js
// execute command in server console
return 'command:~' + 'tell ' + sender + ' Hello world!';

// return msg to sender
return 'message:~' + 'Hello world'
```
:~ - is delimiter, with which you can separate the executed instruction from the returned text. The handler itself can be a simple java switch.

**Comment by DNAmaster10** [comment]
I like this idea. Would you be able to suggest any other functions, such as the message function, which i could implement with the next update? Thanks :)
